version: '3.7'
services:
  backend:
    image: weeee9/simple-web-service
    restart: always
    depends_on:
      - database
    networks:
      - web
    environment:
      - APP_DB_DRIVER=postgres
      - APP_DB_HOST=database
      - APP_DB_PORT=5432
      - APP_DB_USER=service
      - APP_DB_PASSWORD=service
      - APP_DB_DATABASE=service
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-external-labels: "enviroment=staging,name=backend"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backend.localhost`)"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"

  database:
    image: postgres:14-alpine
    restart: always
    networks:
      - web
    environment:
      - POSTGRES_USER=service
      - POSTGRES_PASSWORD=service
      - POSTGRES_DB=service
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:3100/loki/api/v1/push"
        loki-external-labels: "enviroment=staging,name=database"
    labels:
      - "traefik.enable=false"

volumes:
  pg-data:

networks:
  web:
    external: true
