name: docker

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: build and push image
      uses: docker/build-push-action@v2
      with:
        repository: weeee9/simple-web-service
        dockerfile: Dockerfile
        tags: weeee9/simple-web-service:latest
        push: true
        cache-from: type=registry,ref=weeee9/simple-web-service:buildcache
        cache-to: type=registry,ref=weeee9/simple-web-service:buildcache,mode=max